export const SECTORS = [
  {
    id: 'technology',
    name: 'Technology',
    stocks: [
      { sym: 'AAPL',  name: 'Apple' },
      { sym: 'NVDA',  name: 'NVIDIA' },
      { sym: 'MSFT',  name: 'Microsoft' },
      { sym: 'AVGO',  name: 'Broadcom' },
      { sym: 'ORCL',  name: 'Oracle' },
      { sym: 'AMD',   name: 'AMD' },
      { sym: 'QCOM',  name: 'Qualcomm' },
      { sym: 'TXN',   name: 'Texas Instruments' },
      { sym: 'NOW',   name: 'ServiceNow' },
      { sym: 'CSCO',  name: 'Cisco' },
      { sym: 'AMAT',  name: 'Applied Materials' },
      { sym: 'INTC',  name: 'Intel' },
      { sym: 'MU',    name: 'Micron' },
      { sym: 'ADBE',  name: 'Adobe' },
      { sym: 'CRM',   name: 'Salesforce' },
      { sym: 'KLAC',  name: 'KLA Corp' },
      { sym: 'PANW',  name: 'Palo Alto Networks' },
      { sym: 'LRCX',  name: 'Lam Research' },
      { sym: 'IBM',   name: 'IBM' },
      { sym: 'HPQ',   name: 'HP Inc' },
    ],
  },
  {
    id: 'communication',
    name: 'Communication',
    stocks: [
      { sym: 'META',   name: 'Meta' },
      { sym: 'GOOGL',  name: 'Alphabet A' },
      { sym: 'GOOG',   name: 'Alphabet C' },
      { sym: 'NFLX',   name: 'Netflix' },
      { sym: 'DIS',    name: 'Disney' },
      { sym: 'T',      name: 'AT&T' },
      { sym: 'VZ',     name: 'Verizon' },
      { sym: 'CMCSA',  name: 'Comcast' },
      { sym: 'TMUS',   name: 'T-Mobile' },
      { sym: 'CHTR',   name: 'Charter Comm.' },
      { sym: 'TTWO',   name: 'Take-Two Interactive' },
      { sym: 'EA',     name: 'Electronic Arts' },
      { sym: 'WBD',    name: 'Warner Bros. Discovery' },
      { sym: 'OMC',    name: 'Omnicom' },
      { sym: 'IPG',    name: 'Interpublic' },
      { sym: 'PARA',   name: 'Paramount' },
      { sym: 'SIRI',   name: 'SiriusXM' },
      { sym: 'NWSA',   name: 'News Corp A' },
      { sym: 'FOX',    name: 'Fox Corp B' },
      { sym: 'FOXA',   name: 'Fox Corp A' },
    ],
  },
  {
    id: 'consumer-disc',
    name: 'Consumer Disc.',
    stocks: [
      { sym: 'AMZN',  name: 'Amazon' },
      { sym: 'TSLA',  name: 'Tesla' },
      { sym: 'HD',    name: 'Home Depot' },
      { sym: 'MCD',   name: "McDonald's" },
      { sym: 'NKE',   name: 'Nike' },
      { sym: 'LOW',   name: "Lowe's" },
      { sym: 'SBUX',  name: 'Starbucks' },
      { sym: 'TJX',   name: 'TJX Companies' },
      { sym: 'BKNG',  name: 'Booking Holdings' },
      { sym: 'CMG',   name: 'Chipotle' },
      { sym: 'MAR',   name: 'Marriott' },
      { sym: 'YUM',   name: 'Yum! Brands' },
      { sym: 'ORLY',  name: "O'Reilly Auto" },
      { sym: 'AZO',   name: 'AutoZone' },
      { sym: 'ROST',  name: "Ross Stores" },
      { sym: 'DHI',   name: 'D.R. Horton' },
      { sym: 'PHM',   name: 'PulteGroup' },
      { sym: 'F',     name: 'Ford' },
      { sym: 'GM',    name: 'General Motors' },
      { sym: 'LEN',   name: 'Lennar' },
    ],
  },
  {
    id: 'consumer-staples',
    name: 'Consumer Staples',
    stocks: [
      { sym: 'WMT',   name: 'Walmart' },
      { sym: 'PG',    name: 'Procter & Gamble' },
      { sym: 'KO',    name: 'Coca-Cola' },
      { sym: 'COST',  name: 'Costco' },
      { sym: 'PEP',   name: 'PepsiCo' },
      { sym: 'PM',    name: 'Philip Morris' },
      { sym: 'MO',    name: 'Altria' },
      { sym: 'CL',    name: 'Colgate-Palmolive' },
      { sym: 'KMB',   name: 'Kimberly-Clark' },
      { sym: 'GIS',   name: 'General Mills' },
      { sym: 'K',     name: "Kellanova" },
      { sym: 'SYY',   name: 'Sysco' },
      { sym: 'CAG',   name: 'Conagra Brands' },
      { sym: 'HSY',   name: 'Hershey' },
      { sym: 'MKC',   name: 'McCormick' },
      { sym: 'CHD',   name: 'Church & Dwight' },
      { sym: 'HRL',   name: 'Hormel Foods' },
      { sym: 'CPB',   name: 'Campbell Soup' },
      { sym: 'CLX',   name: 'Clorox' },
      { sym: 'TAP',   name: 'Molson Coors' },
    ],
  },
  {
    id: 'healthcare',
    name: 'Healthcare',
    stocks: [
      { sym: 'LLY',   name: 'Eli Lilly' },
      { sym: 'UNH',   name: 'UnitedHealth' },
      { sym: 'JNJ',   name: 'Johnson & Johnson' },
      { sym: 'ABBV',  name: 'AbbVie' },
      { sym: 'MRK',   name: 'Merck' },
      { sym: 'TMO',   name: 'Thermo Fisher' },
      { sym: 'ABT',   name: 'Abbott Labs' },
      { sym: 'DHR',   name: 'Danaher' },
      { sym: 'AMGN',  name: 'Amgen' },
      { sym: 'PFE',   name: 'Pfizer' },
      { sym: 'MDT',   name: 'Medtronic' },
      { sym: 'ISRG',  name: 'Intuitive Surgical' },
      { sym: 'SYK',   name: 'Stryker' },
      { sym: 'VRTX',  name: 'Vertex Pharma' },
      { sym: 'REGN',  name: 'Regeneron' },
      { sym: 'BSX',   name: 'Boston Scientific' },
      { sym: 'CI',    name: 'Cigna' },
      { sym: 'ELV',   name: 'Elevance Health' },
      { sym: 'BMY',   name: 'Bristol-Myers Squibb' },
      { sym: 'ZTS',   name: 'Zoetis' },
    ],
  },
  {
    id: 'financials',
    name: 'Financials',
    stocks: [
      { sym: 'BRK-B', name: 'Berkshire Hathaway' },
      { sym: 'JPM',   name: 'JPMorgan Chase' },
      { sym: 'V',     name: 'Visa' },
      { sym: 'MA',    name: 'Mastercard' },
      { sym: 'BAC',   name: 'Bank of America' },
      { sym: 'WFC',   name: 'Wells Fargo' },
      { sym: 'GS',    name: 'Goldman Sachs' },
      { sym: 'MS',    name: 'Morgan Stanley' },
      { sym: 'AXP',   name: 'American Express' },
      { sym: 'SPGI',  name: 'S&P Global' },
      { sym: 'BLK',   name: 'BlackRock' },
      { sym: 'PGR',   name: 'Progressive' },
      { sym: 'CB',    name: 'Chubb' },
      { sym: 'MMC',   name: 'Marsh & McLennan' },
      { sym: 'USB',   name: 'U.S. Bancorp' },
      { sym: 'C',     name: 'Citigroup' },
      { sym: 'TFC',   name: 'Truist Financial' },
      { sym: 'MET',   name: 'MetLife' },
      { sym: 'AFL',   name: 'Aflac' },
      { sym: 'PNC',   name: 'PNC Financial' },
    ],
  },
  {
    id: 'energy',
    name: 'Energy',
    stocks: [
      { sym: 'XOM',   name: 'ExxonMobil' },
      { sym: 'CVX',   name: 'Chevron' },
      { sym: 'COP',   name: 'ConocoPhillips' },
      { sym: 'SLB',   name: 'SLB' },
      { sym: 'EOG',   name: 'EOG Resources' },
      { sym: 'MPC',   name: 'Marathon Petroleum' },
      { sym: 'VLO',   name: 'Valero Energy' },
      { sym: 'PSX',   name: 'Phillips 66' },
      { sym: 'OXY',   name: 'Occidental' },
      { sym: 'KMI',   name: 'Kinder Morgan' },
      { sym: 'WMB',   name: 'Williams Companies' },
      { sym: 'HES',   name: 'Hess' },
      { sym: 'DVN',   name: 'Devon Energy' },
      { sym: 'BKR',   name: 'Baker Hughes' },
      { sym: 'HAL',   name: 'Halliburton' },
      { sym: 'FANG',  name: 'Diamondback Energy' },
      { sym: 'TRGP',  name: 'Targa Resources' },
      { sym: 'APA',   name: 'APA Corp' },
      { sym: 'MRO',   name: 'Marathon Oil' },
      { sym: 'PR',    name: 'Permian Resources' },
    ],
  },
  {
    id: 'industrials',
    name: 'Industrials',
    stocks: [
      { sym: 'GE',    name: 'GE Aerospace' },
      { sym: 'RTX',   name: 'RTX Corp' },
      { sym: 'HON',   name: 'Honeywell' },
      { sym: 'UPS',   name: 'UPS' },
      { sym: 'LMT',   name: 'Lockheed Martin' },
      { sym: 'CAT',   name: 'Caterpillar' },
      { sym: 'DE',    name: 'John Deere' },
      { sym: 'BA',    name: 'Boeing' },
      { sym: 'UNP',   name: 'Union Pacific' },
      { sym: 'CSX',   name: 'CSX' },
      { sym: 'ETN',   name: 'Eaton' },
      { sym: 'EMR',   name: 'Emerson Electric' },
      { sym: 'ITW',   name: 'Illinois Tool Works' },
      { sym: 'NSC',   name: 'Norfolk Southern' },
      { sym: 'FDX',   name: 'FedEx' },
      { sym: 'MMM',   name: '3M' },
      { sym: 'GD',    name: 'General Dynamics' },
      { sym: 'TDG',   name: 'TransDigm' },
      { sym: 'WM',    name: 'Waste Management' },
      { sym: 'CARR',  name: 'Carrier Global' },
    ],
  },
  {
    id: 'materials',
    name: 'Materials',
    stocks: [
      { sym: 'LIN',   name: 'Linde' },
      { sym: 'SHW',   name: 'Sherwin-Williams' },
      { sym: 'APD',   name: 'Air Products' },
      { sym: 'FCX',   name: 'Freeport-McMoRan' },
      { sym: 'ECL',   name: 'Ecolab' },
      { sym: 'NEM',   name: 'Newmont' },
      { sym: 'DD',    name: 'DuPont' },
      { sym: 'PPG',   name: 'PPG Industries' },
      { sym: 'VMC',   name: 'Vulcan Materials' },
      { sym: 'MLM',   name: 'Martin Marietta' },
      { sym: 'NUE',   name: 'Nucor' },
      { sym: 'ALB',   name: 'Albemarle' },
      { sym: 'CTVA',  name: 'Corteva' },
      { sym: 'MOS',   name: 'Mosaic' },
      { sym: 'IFF',   name: 'Intl Flavors' },
      { sym: 'CF',    name: 'CF Industries' },
      { sym: 'CE',    name: 'Celanese' },
      { sym: 'FMC',   name: 'FMC Corp' },
      { sym: 'SEE',   name: 'Sealed Air' },
      { sym: 'AVY',   name: 'Avery Dennison' },
    ],
  },
  {
    id: 'real-estate',
    name: 'Real Estate',
    stocks: [
      { sym: 'AMT',   name: 'American Tower' },
      { sym: 'PLD',   name: 'Prologis' },
      { sym: 'CCI',   name: 'Crown Castle' },
      { sym: 'EQIX',  name: 'Equinix' },
      { sym: 'PSA',   name: 'Public Storage' },
      { sym: 'O',     name: 'Realty Income' },
      { sym: 'WELL',  name: 'Welltower' },
      { sym: 'DLR',   name: 'Digital Realty' },
      { sym: 'SPG',   name: 'Simon Property' },
      { sym: 'AVB',   name: 'AvalonBay' },
      { sym: 'EQR',   name: 'Equity Residential' },
      { sym: 'VICI',  name: 'VICI Properties' },
      { sym: 'ARE',   name: 'Alexandria RE' },
      { sym: 'MAA',   name: 'Mid-America Apt.' },
      { sym: 'KIM',   name: 'Kimco Realty' },
      { sym: 'REG',   name: 'Regency Centers' },
      { sym: 'WY',    name: 'Weyerhaeuser' },
      { sym: 'EXR',   name: 'Extra Space Storage' },
      { sym: 'HST',   name: 'Host Hotels' },
      { sym: 'UDR',   name: 'UDR Inc.' },
    ],
  },
  {
    id: 'utilities',
    name: 'Utilities',
    stocks: [
      { sym: 'NEE',   name: 'NextEra Energy' },
      { sym: 'SO',    name: 'Southern Company' },
      { sym: 'DUK',   name: 'Duke Energy' },
      { sym: 'AEP',   name: 'American Electric Power' },
      { sym: 'D',     name: 'Dominion Energy' },
      { sym: 'EXC',   name: 'Exelon' },
      { sym: 'PCG',   name: 'PG&E' },
      { sym: 'ED',    name: 'Consolidated Edison' },
      { sym: 'XEL',   name: 'Xcel Energy' },
      { sym: 'SRE',   name: 'Sempra' },
      { sym: 'PEG',   name: 'Public Service Enterprise' },
      { sym: 'AWK',   name: 'American Water Works' },
      { sym: 'AEE',   name: 'Ameren' },
      { sym: 'ES',    name: 'Eversource Energy' },
      { sym: 'CNP',   name: 'CenterPoint Energy' },
      { sym: 'WEC',   name: 'WEC Energy' },
      { sym: 'LNT',   name: 'Alliant Energy' },
      { sym: 'EVRG',  name: 'Evergy' },
      { sym: 'PPL',   name: 'PPL Corp' },
      { sym: 'FE',    name: 'FirstEnergy' },
    ],
  },
]
