export const SEED_INVESTMENTS = [
  // Open positions
  { id:'i001', symbol:'AAPL',  name:'Apple Inc.',            assetType:'Stock', sector:'Technology',             shares:'25',   avgCost:'161.50', currentPrice:'213.00', buyDate:'2024-01-12', status:'open',   stopLoss:'190.00', targetPrice:'240.00', chartLink:'', notes:'Long-term hold, services revenue growth thesis' },
  { id:'i002', symbol:'NVDA',  name:'NVIDIA Corporation',    assetType:'Stock', sector:'Technology',             shares:'15',   avgCost:'495.00', currentPrice:'875.00', buyDate:'2024-02-20', status:'open',   stopLoss:'750.00', targetPrice:'1100.00',chartLink:'', notes:'AI infrastructure supercycle, data center demand' },
  { id:'i003', symbol:'MSFT',  name:'Microsoft Corporation', assetType:'Stock', sector:'Technology',             shares:'10',   avgCost:'374.00', currentPrice:'415.00', buyDate:'2024-03-05', status:'open',   stopLoss:'370.00', targetPrice:'480.00', chartLink:'', notes:'Azure AI growth, Copilot monetization' },
  { id:'i004', symbol:'SPY',   name:'SPDR S&P 500 ETF',      assetType:'ETF',   sector:'ETF / Index',            shares:'20',   avgCost:'490.00', currentPrice:'560.00', buyDate:'2024-01-03', status:'open',   stopLoss:'520.00', targetPrice:'620.00', chartLink:'', notes:'Core index exposure, dollar cost averaging' },
  { id:'i005', symbol:'QQQ',   name:'Invesco Nasdaq-100 ETF',assetType:'ETF',   sector:'ETF / Index',            shares:'15',   avgCost:'415.00', currentPrice:'490.00', buyDate:'2024-01-03', status:'open',   stopLoss:'450.00', targetPrice:'560.00', chartLink:'', notes:'Tech-heavy index, long-term growth' },
  { id:'i006', symbol:'META',  name:'Meta Platforms',        assetType:'Stock', sector:'Communication Services', shares:'8',    avgCost:'358.00', currentPrice:'560.00', buyDate:'2024-02-08', status:'open',   stopLoss:'480.00', targetPrice:'650.00', chartLink:'', notes:'Ad revenue recovery, Reality Labs optionality' },
  { id:'i007', symbol:'AMZN',  name:'Amazon.com Inc.',       assetType:'Stock', sector:'Consumer Discretionary', shares:'12',   avgCost:'175.00', currentPrice:'215.00', buyDate:'2024-03-18', status:'open',   stopLoss:'190.00', targetPrice:'260.00', chartLink:'', notes:'AWS margin expansion, advertising growth' },
  { id:'i008', symbol:'BTC',   name:'Bitcoin',               assetType:'Crypto',sector:'Crypto',                 shares:'0.5',  avgCost:'42000',  currentPrice:'97000',  buyDate:'2024-01-15', status:'open',   stopLoss:'75000',  targetPrice:'150000', chartLink:'', notes:'ETF approval catalyst, halving cycle' },
  { id:'i009', symbol:'ETH',   name:'Ethereum',              assetType:'Crypto',sector:'Crypto',                 shares:'3',    avgCost:'2200',   currentPrice:'3800',   buyDate:'2024-03-01', status:'open',   stopLoss:'2800',   targetPrice:'6000',   chartLink:'', notes:'ETF approval + staking yield' },
  { id:'i010', symbol:'XOM',   name:'Exxon Mobil',           assetType:'Stock', sector:'Energy',                 shares:'30',   avgCost:'102.00', currentPrice:'112.00', buyDate:'2024-04-10', status:'open',   stopLoss:'96.00',  targetPrice:'130.00', chartLink:'', notes:'Dividend yield + energy supercycle hedge' },
  { id:'i011', symbol:'TLT',   name:'iShares 20yr T-Bond',   assetType:'ETF',   sector:'ETF / Index',            shares:'40',   avgCost:'91.00',  currentPrice:'96.00',  buyDate:'2024-09-20', status:'open',   stopLoss:'88.00',  targetPrice:'110.00', chartLink:'', notes:'Rate cut cycle play, duration exposure' },
  { id:'i012', symbol:'GLD',   name:'SPDR Gold Shares',      assetType:'ETF',   sector:'Metals',                 shares:'20',   avgCost:'186.00', currentPrice:'228.00', buyDate:'2024-02-14', status:'open',   stopLoss:'210.00', targetPrice:'260.00', chartLink:'', notes:'Inflation hedge, central bank buying' },

  // Closed positions
  { id:'i013', symbol:'TSLA',  name:'Tesla Inc.',            assetType:'Stock', sector:'Consumer Discretionary', shares:'10',   avgCost:'220.00', currentPrice:'',       buyDate:'2024-01-08', status:'closed', sellPrice:'195.00', sellDate:'2024-04-22', stopLoss:'', targetPrice:'', chartLink:'', notes:'Margin compression concerns, exited at loss' },
  { id:'i014', symbol:'GOOGL', name:'Alphabet Inc.',         assetType:'Stock', sector:'Communication Services', shares:'8',    avgCost:'138.00', currentPrice:'',       buyDate:'2024-01-10', status:'closed', sellPrice:'176.00', sellDate:'2024-07-30', stopLoss:'', targetPrice:'', chartLink:'', notes:'Sold into earnings strength, good run' },
  { id:'i015', symbol:'AMD',   name:'Advanced Micro Devices',assetType:'Stock', sector:'Technology',             shares:'20',   avgCost:'148.00', currentPrice:'',       buyDate:'2024-02-01', status:'closed', sellPrice:'171.00', sellDate:'2024-03-08', stopLoss:'', targetPrice:'', chartLink:'', notes:'Quick trade on AI momentum, took profits' },
  { id:'i016', symbol:'SOFI',  name:'SoFi Technologies',     assetType:'Stock', sector:'Financials',             shares:'200',  avgCost:'8.40',   currentPrice:'',       buyDate:'2024-03-15', status:'closed', sellPrice:'6.80',   sellDate:'2024-06-20', stopLoss:'', targetPrice:'', chartLink:'', notes:'Thesis didn\'t play out, cut losses' },
  { id:'i017', symbol:'SMH',   name:'VanEck Semiconductor',  assetType:'ETF',   sector:'Technology',             shares:'15',   avgCost:'198.00', currentPrice:'',       buyDate:'2024-01-22', status:'closed', sellPrice:'258.00', sellDate:'2024-06-14', stopLoss:'', targetPrice:'', chartLink:'', notes:'Rode the AI chip wave, sold near highs' },
  { id:'i018', symbol:'JPM',   name:'JPMorgan Chase',        assetType:'Stock', sector:'Financials',             shares:'15',   avgCost:'185.00', currentPrice:'',       buyDate:'2024-04-18', status:'closed', sellPrice:'224.00', sellDate:'2024-10-15', stopLoss:'', targetPrice:'', chartLink:'', notes:'Rate environment favorable, strong earnings' },
]
